# --- !Ups

CREATE TABLE "USER" ("NAME" VARCHAR NOT NULL PRIMARY KEY,"PASSWORD" VARCHAR NOT NULL);
CREATE TABLE "TASKS" ("ID" INTEGER NOT NULL PRIMARY KEY, "TASK" VARCHAR NOT NULL, "USERNAME" VARCHAR NOT NULL);

# --- !Downs

DROP TABLE "USER";
DROP TABLE "TASKS";