# --- !Ups

CREATE TABLE "USER" ("NAME" VARCHAR NOT NULL PRIMARY KEY, "PASSWORD" VARCHAR NOT NULL);
CREATE TABLE "TASKS" ("TASK" VARCHAR NOT NULL PRIMARY KEY, "USERNAME" VARCHAR NOT NULL);

# --- !Downs

DROP TABLE "USER";
DROP TABLE "TASKS";